/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppDocumentsIndexRouteImport } from './routes/app.documents.index'
import { Route as AppDocumentsDocIdRouteImport } from './routes/app.documents.$docId'
import { Route as AppDocumentsDocIdIndexRouteImport } from './routes/app.documents.$docId.index'
import { Route as AppDocumentsDocIdOverviewRouteImport } from './routes/app.documents.$docId.overview'
import { Route as AppDocumentsDocIdCategoriesRouteImport } from './routes/app.documents.$docId.categories'
import { Route as AppDocumentsDocIdEndpointsIndexRouteImport } from './routes/app.documents.$docId.endpoints.index'
import { Route as AppDocumentsDocIdEndpointsEndpointIdRouteImport } from './routes/app.documents.$docId.endpoints.$endpointId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocIdRoute = AppDocumentsDocIdRouteImport.update({
  id: '/documents/$docId',
  path: '/documents/$docId',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsDocIdIndexRoute = AppDocumentsDocIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsDocIdRoute,
} as any)
const AppDocumentsDocIdOverviewRoute =
  AppDocumentsDocIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppDocumentsDocIdRoute,
  } as any)
const AppDocumentsDocIdCategoriesRoute =
  AppDocumentsDocIdCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AppDocumentsDocIdRoute,
  } as any)
const AppDocumentsDocIdEndpointsIndexRoute =
  AppDocumentsDocIdEndpointsIndexRouteImport.update({
    id: '/endpoints/',
    path: '/endpoints/',
    getParentRoute: () => AppDocumentsDocIdRoute,
  } as any)
const AppDocumentsDocIdEndpointsEndpointIdRoute =
  AppDocumentsDocIdEndpointsEndpointIdRouteImport.update({
    id: '/endpoints/$endpointId',
    path: '/endpoints/$endpointId',
    getParentRoute: () => AppDocumentsDocIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents/$docId': typeof AppDocumentsDocIdRouteWithChildren
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/documents/$docId/categories': typeof AppDocumentsDocIdCategoriesRoute
  '/app/documents/$docId/overview': typeof AppDocumentsDocIdOverviewRoute
  '/app/documents/$docId/': typeof AppDocumentsDocIdIndexRoute
  '/app/documents/$docId/endpoints/$endpointId': typeof AppDocumentsDocIdEndpointsEndpointIdRoute
  '/app/documents/$docId/endpoints/': typeof AppDocumentsDocIdEndpointsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents': typeof AppDocumentsIndexRoute
  '/app/documents/$docId/categories': typeof AppDocumentsDocIdCategoriesRoute
  '/app/documents/$docId/overview': typeof AppDocumentsDocIdOverviewRoute
  '/app/documents/$docId': typeof AppDocumentsDocIdIndexRoute
  '/app/documents/$docId/endpoints/$endpointId': typeof AppDocumentsDocIdEndpointsEndpointIdRoute
  '/app/documents/$docId/endpoints': typeof AppDocumentsDocIdEndpointsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/documents/$docId': typeof AppDocumentsDocIdRouteWithChildren
  '/app/documents/': typeof AppDocumentsIndexRoute
  '/app/documents/$docId/categories': typeof AppDocumentsDocIdCategoriesRoute
  '/app/documents/$docId/overview': typeof AppDocumentsDocIdOverviewRoute
  '/app/documents/$docId/': typeof AppDocumentsDocIdIndexRoute
  '/app/documents/$docId/endpoints/$endpointId': typeof AppDocumentsDocIdEndpointsEndpointIdRoute
  '/app/documents/$docId/endpoints/': typeof AppDocumentsDocIdEndpointsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/documents/$docId'
    | '/app/documents/'
    | '/app/documents/$docId/categories'
    | '/app/documents/$docId/overview'
    | '/app/documents/$docId/'
    | '/app/documents/$docId/endpoints/$endpointId'
    | '/app/documents/$docId/endpoints/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/documents'
    | '/app/documents/$docId/categories'
    | '/app/documents/$docId/overview'
    | '/app/documents/$docId'
    | '/app/documents/$docId/endpoints/$endpointId'
    | '/app/documents/$docId/endpoints'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/app/dashboard'
    | '/app/documents/$docId'
    | '/app/documents/'
    | '/app/documents/$docId/categories'
    | '/app/documents/$docId/overview'
    | '/app/documents/$docId/'
    | '/app/documents/$docId/endpoints/$endpointId'
    | '/app/documents/$docId/endpoints/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/': {
      id: '/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/$docId': {
      id: '/app/documents/$docId'
      path: '/documents/$docId'
      fullPath: '/app/documents/$docId'
      preLoaderRoute: typeof AppDocumentsDocIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents/$docId/': {
      id: '/app/documents/$docId/'
      path: '/'
      fullPath: '/app/documents/$docId/'
      preLoaderRoute: typeof AppDocumentsDocIdIndexRouteImport
      parentRoute: typeof AppDocumentsDocIdRoute
    }
    '/app/documents/$docId/overview': {
      id: '/app/documents/$docId/overview'
      path: '/overview'
      fullPath: '/app/documents/$docId/overview'
      preLoaderRoute: typeof AppDocumentsDocIdOverviewRouteImport
      parentRoute: typeof AppDocumentsDocIdRoute
    }
    '/app/documents/$docId/categories': {
      id: '/app/documents/$docId/categories'
      path: '/categories'
      fullPath: '/app/documents/$docId/categories'
      preLoaderRoute: typeof AppDocumentsDocIdCategoriesRouteImport
      parentRoute: typeof AppDocumentsDocIdRoute
    }
    '/app/documents/$docId/endpoints/': {
      id: '/app/documents/$docId/endpoints/'
      path: '/endpoints'
      fullPath: '/app/documents/$docId/endpoints/'
      preLoaderRoute: typeof AppDocumentsDocIdEndpointsIndexRouteImport
      parentRoute: typeof AppDocumentsDocIdRoute
    }
    '/app/documents/$docId/endpoints/$endpointId': {
      id: '/app/documents/$docId/endpoints/$endpointId'
      path: '/endpoints/$endpointId'
      fullPath: '/app/documents/$docId/endpoints/$endpointId'
      preLoaderRoute: typeof AppDocumentsDocIdEndpointsEndpointIdRouteImport
      parentRoute: typeof AppDocumentsDocIdRoute
    }
  }
}

interface AppDocumentsDocIdRouteChildren {
  AppDocumentsDocIdCategoriesRoute: typeof AppDocumentsDocIdCategoriesRoute
  AppDocumentsDocIdOverviewRoute: typeof AppDocumentsDocIdOverviewRoute
  AppDocumentsDocIdIndexRoute: typeof AppDocumentsDocIdIndexRoute
  AppDocumentsDocIdEndpointsEndpointIdRoute: typeof AppDocumentsDocIdEndpointsEndpointIdRoute
  AppDocumentsDocIdEndpointsIndexRoute: typeof AppDocumentsDocIdEndpointsIndexRoute
}

const AppDocumentsDocIdRouteChildren: AppDocumentsDocIdRouteChildren = {
  AppDocumentsDocIdCategoriesRoute: AppDocumentsDocIdCategoriesRoute,
  AppDocumentsDocIdOverviewRoute: AppDocumentsDocIdOverviewRoute,
  AppDocumentsDocIdIndexRoute: AppDocumentsDocIdIndexRoute,
  AppDocumentsDocIdEndpointsEndpointIdRoute:
    AppDocumentsDocIdEndpointsEndpointIdRoute,
  AppDocumentsDocIdEndpointsIndexRoute: AppDocumentsDocIdEndpointsIndexRoute,
}

const AppDocumentsDocIdRouteWithChildren =
  AppDocumentsDocIdRoute._addFileChildren(AppDocumentsDocIdRouteChildren)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocumentsDocIdRoute: typeof AppDocumentsDocIdRouteWithChildren
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppDocumentsDocIdRoute: AppDocumentsDocIdRouteWithChildren,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
