-- Rota V010 — monotonic sequence column for deterministic audit chain ordering.
--
-- record_hash chains by prev_hash, but to find "the previous row for this tenant" we need a
-- strict total order; occurred_at (microsecond) can tie when several events are written in the
-- same flush. An identity column gives an unambiguous, append-time order. It uses an implicit
-- identity sequence, so no extra sequence GRANT is needed for rota_app (table INSERT suffices).

ALTER TABLE audit.events ADD COLUMN seq BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX idx_audit_events_tenant_seq ON audit.events (tenant_id, seq DESC);
